s1=int(input("Enter your marks: "))
s2=int(input("Enter your marks: "))
s3=int(input("Enter your marks: "))
s4=int(input("Enter your marks: "))
s5=int(input("Enter your marks: "))
s6=int(input("Enter your marks: "))
marks=[s1,s2,s3,s4,s5,s6]
print(marks)
marks.sort()
print(marks)